linters:
  disable-all: true
  enable:
    - errcheck
    - gocognit
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10

run:
  timeout: 5m
  skip-dirs:
    - vendor

issues:
  exclude-use-default: false
